/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-09-10 13:14:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin.adminMember;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.admin.adminMember.model.vo.Report;
import com.kh.common.model.PageInfo;
import com.kh.member.model.vo.Member;
import java.util.ArrayList;
import com.kh.member.model.vo.Member;

public final class adminMemberReprotListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/views/common/header2.jsp", Long.valueOf(1657177826000L));
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1657072068000L));
    _jspx_dependants.put("/views/common/adminMenu.jsp", Long.valueOf(1657171274000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.PageInfo");
    _jspx_imports_classes.add("com.kh.admin.adminMember.model.vo.Report");
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Report> list = (ArrayList<Report>) request.getAttribute("list");
PageInfo pi = (PageInfo) request.getAttribute("pi");

int currentPage = pi.getCurrentPage();
int startPage = pi.getStartPage();
int endPage = pi.getEndPage();
int maxPage = pi.getMaxPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원관리 - 신고내역</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\" />\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\n");
      out.write("    \n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String alertMsg = (String)session.getAttribute("alertMsg");
	
	String contextPath = request.getContextPath();

    request.getParameter("categoryNo");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" as=\"style\" crossorigin href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.4/dist/web/static/pretendard.css\" />\n");
      out.write("    <title>Document</title>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            box-sizing : border-box;\n");
      out.write("            /*border : 1px solid red;*/\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        .wrap{\n");
      out.write("            width : 1000px;\n");
      out.write("            height : 80px;\n");
      out.write("            margin : auto;\n");
      out.write("        }\n");
      out.write("        .warp > div{width : 100%;}\n");
      out.write("\n");
      out.write("        /*헤더*/\n");
      out.write("        #header{height : 100%; margin-bottom: 10px;}\n");
      out.write("        #header > div{height : 100%; float : left;}\n");
      out.write("        #header_1{width : 15%; text-align: center;}\n");
      out.write("        #header_2{width : 30%; position : relative;}\n");
      out.write("        #header_3{width : 55%; text-align: right;}\n");
      out.write("        #header_3 a{text-decoration: none;color: black;}\n");
      out.write("        #etc{margin-top: 50px; width: 100%; height: 40px;}\n");
      out.write("        #userImg{width: auto; height: auto;}\n");
      out.write("		*{font-family: Pretendard;}\n");
      out.write("        \n");
      out.write("        /*로고*/\n");
      out.write("        #logo{width: 100px; margin-top: 30px;}\n");
      out.write("\n");
      out.write("        /*검색창*/\n");
      out.write("        #search_form {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 35%;\n");
      out.write("            position: absolute;\n");
      out.write("            right: 0;\n");
      out.write("            top : 40px;\n");
      out.write("            left: 0;\n");
      out.write("            bottom : 0;\n");
      out.write("        }\n");
      out.write("        #search_form>div{\n");
      out.write("            float:left;\n");
      out.write("        }\n");
      out.write("        #search_text{\n");
      out.write("            width:220px;\n");
      out.write("            height: 35px;\n");
      out.write("        }\n");
      out.write("        #search_btn{\n");
      out.write("            width: 23px;\n");
      out.write("            height: 23px;\n");
      out.write("            margin-top: 6px;\n");
      out.write("            margin-left: 5px;\n");
      out.write("            opacity: 0.8;\n");
      out.write("        }\n");
      out.write("        #search_form input{\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            width:100%;\n");
      out.write("            height: 100%;\n");
      out.write("        }\n");
      out.write("        input:focus {outline:none;}\n");
      out.write("        #searchI{\n");
      out.write("            border-top: 0;\n");
      out.write("            border-left: 0;\n");
      out.write("            border-right: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        /*category*/\n");
      out.write("        #category{\n");
      out.write("            width:1000px; \n");
      out.write("            height: 40px;\n");
      out.write("            margin: auto;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        #category > div{\n");
      out.write("            height : 100%;\n");
      out.write("            float : left;\n");
      out.write("        }\n");
      out.write("        #categoryHover{\n");
      out.write("            width: 10%; \n");
      out.write("            text-align: right; \n");
      out.write("            float: left;\n");
      out.write("        }\n");
      out.write("        #categoryHover a{\n");
      out.write("            display: inline-block; \n");
      out.write("            font-size: 20px; \n");
      out.write("            margin-top: 12px;\n");
      out.write("        }\n");
      out.write("        #categoryList{\n");
      out.write("            width: 85%; \n");
      out.write("            text-align: left;\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        #categoryList li{\n");
      out.write("            list-style-type : none; \n");
      out.write("            float: left; \n");
      out.write("            width : auto; \n");
      out.write("            height: 100%;\n");
      out.write("            margin-right: 20px;\n");
      out.write("        }\n");
      out.write("        #categoryList a{\n");
      out.write("            text-decoration: none; \n");
      out.write("            color: black;\n");
      out.write("            width: auto;\n");
      out.write("        }\n");
      out.write("        #categoryHover>img{\n");
      out.write("            width: 15px; \n");
      out.write("            height: 15px;\n");
      out.write("        }\n");
      out.write("        #categoryList>ul>li>a:hover{\n");
      out.write("            color: rgb(232, 215, 66);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*자동완성시 배경색 없애기*/\n");
      out.write("        input:-webkit-autofill {\n");
      out.write("            -webkit-box-shadow: 0 0 0 1000px #ffffff inset;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <div id=\"header_1\">\n");
      out.write("            	<a href=\"");
      out.print( contextPath );
      out.write("\">\n");
      out.write("            		<img src=\"./resources/img/WeFunD.png\" id=\"logo\" >\n");
      out.write("            	</a>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div id=\"header_2\">\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (loginUser == null) { 
      out.write("\n");
      out.write("	            <div id=\"header_3\">\n");
      out.write("	                <div id=\"etc\">\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\">로그인</a>&nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/signUpForm.me\">회원가입</a>&nbsp;\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("            ");
 } else if(loginUser.getUserId().equals("admin")) { 
      out.write("\n");
      out.write("            	<!-- 관리자화면 마이페이지->QnA페이지 -->\n");
      out.write("                <div id=\"header_3\">\n");
      out.write("                    <div id=\"etc\">\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/adminlist.qna?cpage=1\">\n");
      out.write("                            <img src=\"./resources/img/user.png\" id=\"userImg\" style=\"width: 15px; height:15px;\"> &nbsp;\n");
      out.write("                        </a>\n");
      out.write("                        ");
      out.print( loginUser.getNickname() );
      out.write(" 님&nbsp;&nbsp;&nbsp;\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("	            <!-- 로그인 성공 시 화면 -->\n");
      out.write("	            <div id=\"header_3\">\n");
      out.write("	                <div id=\"etc\">\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/EnrollForm.pj\">프로젝트 업로드</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("	                    \n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/myPage.me?userNo=");
      out.print( loginUser.getUserNo() );
      out.write("\">\n");
      out.write("	                    <img src=\"./resources/img/user.png\" id=\"userImg\" style=\"width: 15px; height:15px;\">&nbsp\n");
      out.write("	                    ");
      out.print( loginUser.getNickname() );
      out.write(" 님</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("            ");
 } 
      out.write(" \n");
      out.write("		</div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    \n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\";\n");
      out.write("		\n");
      out.write("		var loginForm = document.getElementById(\"login-form\");\n");
      out.write("     \n");
      out.write("		console.log(msg);\n");
      out.write("     \n");
      out.write("		if(msg != \"null\"){\n");
      out.write("			alert(msg);\n");
      out.write("          ");
 session.removeAttribute("alertMsg"); 
      out.write("\n");
      out.write("		}\n");
      out.write("     	\n");
      out.write("	</script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write(".adminMenu a {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"] {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"]+label {\r\n");
      out.write("	display: block;\r\n");
      out.write("	cursor: pointer;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"]+label+div {\r\n");
      out.write("	max-height: 0;\r\n");
      out.write("	transition: all 0.5s;\r\n");
      out.write("	overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"]:checked+label+div {\r\n");
      out.write("	max-height: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"]+label img {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	top: 50%;\r\n");
      out.write("	right: 10px;\r\n");
      out.write("	width: 20px;\r\n");
      out.write("	height: 20px;\r\n");
      out.write("	margin-top: -10px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	background: 0 0 no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[id*=\"answer\"]:checked+label img {\r\n");
      out.write("	background-position: 0 -30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminMenu {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-left: 6%;\r\n");
      out.write("\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminMenu label:hover {\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	color: rgb(63, 74, 224);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminMenu a:hover {\r\n");
      out.write("	font-size: 26px;\r\n");
      out.write("	color: rgb(63, 74, 224);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adminMenu div {\r\n");
      out.write("	margin-bottom: 25px;\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".title {\r\n");
      out.write("	font-size: xx-large;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media ( max-width : 1680px ) {\r\n");
      out.write("	.adminMenu {\r\n");
      out.write("		display: none;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("<!--위-->\r\n");
      out.write(".maincontent table {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table a {\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table th {\r\n");
      out.write("	color: #495057;\r\n");
      out.write("	background-color: #e9ecef;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#maincontent {\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-right: 25%;\r\n");
      out.write("	margin-top: 3%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".selectPage {\r\n");
      out.write("	width: 64%;\r\n");
      out.write("	float: right;\r\n");
      out.write("	margin-right: 17%;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: block;\r\n");
      out.write("	height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnYellow {\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: rgb(255, 217, 72);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btnYellow:hover {\r\n");
      out.write("	background-color: rgb(255, 190, 18);\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
 if(loginUser!=null && loginUser.getUserId().equals("admin")) {
      out.write("\r\n");
      out.write("	<div class=\"adminMenu\">\r\n");
      out.write("		<p class=\"title\">관리자 페이지</p>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<div class=\"accordion\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"answer01\" /> <label for=\"answer01\">\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/adminlist.qna?cpage=1\">Q&A</a>\r\n");
      out.write("			</label>\r\n");
      out.write("		</div>\r\n");
      out.write("			\r\n");
      out.write("		<div class=\"accordion\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"answer02\" /> <label for=\"answer02\">프로젝트<img\r\n");
      out.write("				alt=\"\"\r\n");
      out.write("				src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKKs6OP36GlHnJCLBRA3bwO1RYfLy9VLUesg&usqp=CAU\"></label>\r\n");
      out.write("			<div>\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/adminlist.pj?cpage=1&type=all\"> - 프로젝트 상태</a>\r\n");
      out.write("				<br /> <a href=\"");
      out.print(contextPath);
      out.write("//adminList.sup?cpage=1\"> - 구매 내역</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"accordion\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"answer03\" /> <label for=\"answer03\">회원<img\r\n");
      out.write("				alt=\"\"\r\n");
      out.write("				src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKKs6OP36GlHnJCLBRA3bwO1RYfLy9VLUesg&usqp=CAU\"></label>\r\n");
      out.write("			<div>\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/adminRepolist.mem?cpage=1\"> - 회원 신고 내역</a>\r\n");
      out.write("				<br /> <a href=\"");
      out.print(contextPath);
      out.write("/adminlist.mem?cpage=1\"> - 회원조회</a>\r\n");
      out.write("				<br /> <a href=\"");
      out.print(contextPath);
      out.write("/adminWRlist.mem?cpage=1\"> - 탈퇴회원 조회 / 복구</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"accordion\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"answer04\" /> <label for=\"answer04\">게시판<img\r\n");
      out.write("				alt=\"\"\r\n");
      out.write("				src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKKs6OP36GlHnJCLBRA3bwO1RYfLy9VLUesg&usqp=CAU\"></label>\r\n");
      out.write("			<div>\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/list.no?cpage=1\"> - 공지글</a> <br /> <a\r\n");
      out.write("					href=\"");
      out.print(contextPath);
      out.write("/adminlist.re?cpage=1\"> - 리뷰</a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"accordion\">\r\n");
      out.write("			<input type=\"checkbox\" id=\"answer04\" /> <label for=\"answer04\">\r\n");
      out.write("				<a href=\"");
      out.print(contextPath);
      out.write("/adminlist.sa\">매출</a>\r\n");
      out.write("\r\n");
      out.write("			</label>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	");
 } else  { 
      out.write("	\r\n");
      out.write("		<br><br><br><br><p style=\"text-align: center; font-size: xx-large; color: red\" > 관리자 페이지 입니다</p>\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write('	');
 if(loginUser!=null && loginUser.getUserId().equals("admin")) {
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div id=\"maincontent\">\r\n");
      out.write("		<p class=\"title\">회원관리 - 신고내역</p>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<br> <br>\r\n");
      out.write("		<div>\r\n");
      out.write("			<table class=\"table\">\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th width=\"150px\">댓글 번호</th>\r\n");
      out.write("					<th width=\"600px\">글 제목</th>\r\n");
      out.write("					<th width=\"150px\">댓글 작성자</th>\r\n");
      out.write("					<th width=\"200px\">작성일</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>회원 정지</th>\r\n");
      out.write("					<th>신고내역</th>\r\n");
      out.write("					<th>신고자</th>\r\n");
      out.write("					<th>신고일자</th>\r\n");
      out.write("				</tr>\r\n");
      out.write("\r\n");
      out.write("				");
 if (list.isEmpty()) { 
      out.write("\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td colspan=\"4\">신고내역이 존재하지 않습니다</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("					");
 for (Report r : list) { 
      out.write("\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>");
      out.print(r.getReplyNo());
      out.write("</td>\r\n");
      out.write("							<td><a href=\"");
      out.print( contextPath );
      out.write("/detail.rv?rno=");
      out.print(r.getReviewNo());
      out.write('"');
      out.write('>');
      out.print(r.getReviewTitle());
      out.write("</a></td>\r\n");
      out.write("							<td>");
      out.print(r.getReplyWriter());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(r.getReplyDate().substring(0, 16));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<button class=\"btn-modal btn btn-dark\" data-toggle=\"modal\"\r\n");
      out.write("									data-target=\"#myModal\" data-id=\"");
      out.print(r.getReplyWriter());
      out.write(',');
      out.print( r.getReplyNo());
      out.write("\">회원정지</button>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>");
      out.print(r.getReplyContent());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(r.getReplyReporter());
      out.write("</td>\r\n");
      out.write("							<td>");
      out.print(r.getReportDate().substring(0, 16));
      out.write("</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					");
 } 
      out.write("\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- The Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"myModal\">\r\n");
      out.write("		<div class=\"modal-dialog\">\r\n");
      out.write("			<div class=\"modal-content\">\r\n");
      out.write("				<!-- Modal Header -->\r\n");
      out.write("				<div class=\"modal-header\">\r\n");
      out.write("					<h4 class=\"modal-title\" style=\"text-align: center;\">\r\n");
      out.write("						<br>해당 회원을 정지하겠습니까?<br>\r\n");
      out.write("					</h4>\r\n");
      out.write("					<button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Modal footer -->\r\n");
      out.write("				<div class=\"modal-footer\">\r\n");
      out.write("					<form action=\"");
      out.print( contextPath );
      out.write("/suspension.mem\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" class=\"body-contents\" id=\"nickname\" name=\"nickname\">\r\n");
      out.write("						<input type=\"hidden\" class=\"body-contents\" id=\"replyNo\" name=\"replyNo\">\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-danger\">정지</button>\r\n");
      out.write("					</form>\r\n");
      out.write("					\r\n");
      out.write("					<form action=\"");
      out.print( contextPath );
      out.write("/check.mem\" method=\"post\">\r\n");
      out.write("						<input type=\"hidden\" class=\"body-contents\" id=\"replyNo\" name=\"replyNo\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-danger\">확인</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("	$(\".btn-modal\").click(function(){\r\n");
      out.write("		var data = $(this).data('id');\r\n");
      out.write("		var nickname = data.split(',');		\r\n");
      out.write("    	$(\"#nickname\").val(nickname[0]);\r\n");
      out.write("    	$(\"#replyNo\").val(nickname[1]);\r\n");
      out.write("	console.log(data);\r\n");
      out.write("	console.log(nickname[0]);\r\n");
      out.write("	\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"selectPage\">\r\n");
      out.write("		<div>\r\n");
      out.write("			");
 if (currentPage != 1) { 
      out.write("\r\n");
      out.write("				<button onclick=\"location.href='");
      out.print(contextPath);
      out.write("/adminRepolist.mem?cpage=");
      out.print(currentPage - 1);
      out.write("'\" class=\"btn  btnYellow\">&lt;</button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
 for (int i = startPage; i <= endPage; i++) { 
      out.write("\r\n");
      out.write("				");
 if (i != currentPage) { 
      out.write("\r\n");
      out.write("					<button onclick=\"location.href='");
      out.print(contextPath);
      out.write("/adminRepolist.mem?cpage=");
      out.print(i);
      out.write("'\" class=\"btn  btnYellow\">");
      out.print(i);
      out.write("</button>\r\n");
      out.write("				");
 } else { 
      out.write("\r\n");
      out.write("					<button style=\"background: rgb(255,240,110)\" class=\"btn  btnYellow\">");
      out.print(i);
      out.write("</button>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("			");
 if (currentPage != maxPage && 0 != maxPage) { 
      out.write("\r\n");
      out.write("				<button onclick=\"location.href='");
      out.print(contextPath);
      out.write("/adminRepolist.mem?cpage=");
      out.print(currentPage + 1);
      out.write("'\" class=\"btn  btnYellow\">&gt;</button>\r\n");
      out.write("			");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("	");
 } else  { 
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("	");
 } 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<br clear=\"both\">\r\n");
      out.write("	");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            box-sizing : border-box;\n");
      out.write("            /*border : 1px solid red;*/\n");
      out.write("        }\n");
      out.write("        .wrap{\n");
      out.write("            width : 1000px;\n");
      out.write("            height : 80px;\n");
      out.write("            margin : auto;\n");
      out.write("        }\n");
      out.write("        .warp > div{width : 100%;}\n");
      out.write("        \n");
      out.write("        /*footer*/\n");
      out.write("        #footer{height: 130px; text-align: left;}\n");
      out.write("        #footer > div{height : 100%; float : left;}\n");
      out.write("        #footer1{width: 60%; margin-left: 25px; }\n");
      out.write("        #footer2{ width: 20%; margin-left: 50px;}\n");
      out.write("        #footer p{font-size: 12px;}\n");
      out.write("        #footer a{text-decoration: none; color: rgb(63, 74, 224);}\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("    \n");
      out.write("        <div id=\"footer\">\n");
      out.write("\n");
      out.write("            <hr>\n");
      out.write("\n");
      out.write("            <div id=\"footer1\"> \n");
      out.write("                <p style=\"font-size: 15px;\">WeFun:D</p>\n");
      out.write("                <p>주소 : 서울특별시 중구 남대문로 120 대일빌딩 2F</p>\n");
      out.write("                <p>대표 : 이승철</p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"footer2\"> \n");
      out.write("                <p style=\"font-size: 15px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.not?cpage=1\">고객센터</a></p>\n");
      out.write("                <p>이용약관</p>\n");
      out.write("                <p>개인정보처리방침</p>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div id=\"footer3\"> \n");
      out.write("                <p style=\"font-size: 15px;\">운영시간</p>\n");
      out.write("                <p>평일 10:00~17:00</p>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
