/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2022-09-10 13:13:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.member.model.vo.Member;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/member/../common/header2.jsp", Long.valueOf(1657177826000L));
    _jspx_dependants.put("/views/member/../common/footer.jsp", Long.valueOf(1657072068000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");

	String errorMsg = (String)request.getAttribute("errorMsg");
    System.out.println(errorMsg);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>로그인</title>\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            box-sizing : border-box;\n");
      out.write("            /*border : 1px solid red;*/\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        /*login*/\n");
      out.write("        #loginP{\n");
      out.write("            font-size: 32px;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        #outer{\n");
      out.write("            width : 1000px;\n");
      out.write("            height : 800px;\n");
      out.write("            margin : auto;\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        #login{\n");
      out.write("            width: 350px;\n");
      out.write("            height: 400px;\n");
      out.write("            text-align: center;\n");
      out.write("            margin: auto;\n");
      out.write("            margin-top: 100px;\n");
      out.write("        }\n");
      out.write("        #userId, #userPwd{\n");
      out.write("            border-top: 0;\n");
      out.write("            border-left: 0;\n");
      out.write("            border-right: 0;\n");
      out.write("            margin-top: 10px;\n");
      out.write("        }\n");
      out.write("        #userId, #userPwd, #loginBtn{\n");
      out.write("            width: 230px;\n");
      out.write("            height: 30px;\n");
      out.write("        }\n");
      out.write("        #userPwd{\n");
      out.write("            margin-top: 20px;\n");
      out.write("            margin-bottom: 10px;\n");
      out.write("        }\n");
      out.write("        #idSaveP, #searchIdPwd{\n");
      out.write("            font-size: 15px;\n");
      out.write("        }\n");
      out.write("        #searchIdPwd{\n");
      out.write("            text-decoration: none; \n");
      out.write("            cursor: pointer; \n");
      out.write("            color: black;\n");
      out.write("        }\n");
      out.write("        #loginBtn{\n");
      out.write("            background-color: rgb(247, 217, 58);\n");
      out.write("            border: none;\n");
      out.write("            cursor: pointer;\n");
      out.write("        }\n");
      out.write("        #loginBtn:hover{\n");
      out.write("            opacity: 0.8;\n");
      out.write("        }\n");
      out.write("        #signUp{\n");
      out.write("            color: rgb(63, 74, 224);\n");
      out.write("            font-size: 15px;\n");
      out.write("            text-decoration : none;\n");
      out.write("        }\n");
      out.write("        #hr{\n");
      out.write("            width: 250px;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	");
 com.kh.common.JDBCTemplate.getConnection(); 
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("    \n");

	Member loginUser = (Member)session.getAttribute("loginUser");

	String alertMsg = (String)session.getAttribute("alertMsg");
	
	String contextPath = request.getContextPath();

    request.getParameter("categoryNo");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <link rel=\"stylesheet\" as=\"style\" crossorigin href=\"https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.4/dist/web/static/pretendard.css\" />\n");
      out.write("    <title>Document</title>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            box-sizing : border-box;\n");
      out.write("            /*border : 1px solid red;*/\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        .wrap{\n");
      out.write("            width : 1000px;\n");
      out.write("            height : 80px;\n");
      out.write("            margin : auto;\n");
      out.write("        }\n");
      out.write("        .warp > div{width : 100%;}\n");
      out.write("\n");
      out.write("        /*헤더*/\n");
      out.write("        #header{height : 100%; margin-bottom: 10px;}\n");
      out.write("        #header > div{height : 100%; float : left;}\n");
      out.write("        #header_1{width : 15%; text-align: center;}\n");
      out.write("        #header_2{width : 30%; position : relative;}\n");
      out.write("        #header_3{width : 55%; text-align: right;}\n");
      out.write("        #header_3 a{text-decoration: none;color: black;}\n");
      out.write("        #etc{margin-top: 50px; width: 100%; height: 40px;}\n");
      out.write("        #userImg{width: auto; height: auto;}\n");
      out.write("		*{font-family: Pretendard;}\n");
      out.write("        \n");
      out.write("        /*로고*/\n");
      out.write("        #logo{width: 100px; margin-top: 30px;}\n");
      out.write("\n");
      out.write("        /*검색창*/\n");
      out.write("        #search_form {\n");
      out.write("            width: 100%;\n");
      out.write("            height: 35%;\n");
      out.write("            position: absolute;\n");
      out.write("            right: 0;\n");
      out.write("            top : 40px;\n");
      out.write("            left: 0;\n");
      out.write("            bottom : 0;\n");
      out.write("        }\n");
      out.write("        #search_form>div{\n");
      out.write("            float:left;\n");
      out.write("        }\n");
      out.write("        #search_text{\n");
      out.write("            width:220px;\n");
      out.write("            height: 35px;\n");
      out.write("        }\n");
      out.write("        #search_btn{\n");
      out.write("            width: 23px;\n");
      out.write("            height: 23px;\n");
      out.write("            margin-top: 6px;\n");
      out.write("            margin-left: 5px;\n");
      out.write("            opacity: 0.8;\n");
      out.write("        }\n");
      out.write("        #search_form input{\n");
      out.write("            box-sizing: border-box;\n");
      out.write("            width:100%;\n");
      out.write("            height: 100%;\n");
      out.write("        }\n");
      out.write("        input:focus {outline:none;}\n");
      out.write("        #searchI{\n");
      out.write("            border-top: 0;\n");
      out.write("            border-left: 0;\n");
      out.write("            border-right: 0;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        /*category*/\n");
      out.write("        #category{\n");
      out.write("            width:1000px; \n");
      out.write("            height: 40px;\n");
      out.write("            margin: auto;\n");
      out.write("            margin-top: 20px;\n");
      out.write("        }\n");
      out.write("        #category > div{\n");
      out.write("            height : 100%;\n");
      out.write("            float : left;\n");
      out.write("        }\n");
      out.write("        #categoryHover{\n");
      out.write("            width: 10%; \n");
      out.write("            text-align: right; \n");
      out.write("            float: left;\n");
      out.write("        }\n");
      out.write("        #categoryHover a{\n");
      out.write("            display: inline-block; \n");
      out.write("            font-size: 20px; \n");
      out.write("            margin-top: 12px;\n");
      out.write("        }\n");
      out.write("        #categoryList{\n");
      out.write("            width: 85%; \n");
      out.write("            text-align: left;\n");
      out.write("            display: none;\n");
      out.write("        }\n");
      out.write("        #categoryList li{\n");
      out.write("            list-style-type : none; \n");
      out.write("            float: left; \n");
      out.write("            width : auto; \n");
      out.write("            height: 100%;\n");
      out.write("            margin-right: 20px;\n");
      out.write("        }\n");
      out.write("        #categoryList a{\n");
      out.write("            text-decoration: none; \n");
      out.write("            color: black;\n");
      out.write("            width: auto;\n");
      out.write("        }\n");
      out.write("        #categoryHover>img{\n");
      out.write("            width: 15px; \n");
      out.write("            height: 15px;\n");
      out.write("        }\n");
      out.write("        #categoryList>ul>li>a:hover{\n");
      out.write("            color: rgb(232, 215, 66);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        /*자동완성시 배경색 없애기*/\n");
      out.write("        input:-webkit-autofill {\n");
      out.write("            -webkit-box-shadow: 0 0 0 1000px #ffffff inset;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <div id=\"header_1\">\n");
      out.write("            	<a href=\"");
      out.print( contextPath );
      out.write("\">\n");
      out.write("            		<img src=\"./resources/img/WeFunD.png\" id=\"logo\" >\n");
      out.write("            	</a>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div id=\"header_2\">\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");
 if (loginUser == null) { 
      out.write("\n");
      out.write("	            <div id=\"header_3\">\n");
      out.write("	                <div id=\"etc\">\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/loginForm.me\">로그인</a>&nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/signUpForm.me\">회원가입</a>&nbsp;\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("            ");
 } else if(loginUser.getUserId().equals("admin")) { 
      out.write("\n");
      out.write("            	<!-- 관리자화면 마이페이지->QnA페이지 -->\n");
      out.write("                <div id=\"header_3\">\n");
      out.write("                    <div id=\"etc\">\n");
      out.write("                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/adminlist.qna?cpage=1\">\n");
      out.write("                            <img src=\"./resources/img/user.png\" id=\"userImg\" style=\"width: 15px; height:15px;\"> &nbsp;\n");
      out.write("                        </a>\n");
      out.write("                        ");
      out.print( loginUser.getNickname() );
      out.write(" 님&nbsp;&nbsp;&nbsp;\n");
      out.write("                        <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            \n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("	            <!-- 로그인 성공 시 화면 -->\n");
      out.write("	            <div id=\"header_3\">\n");
      out.write("	                <div id=\"etc\">\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/list.rv?cpage=1\">리뷰게시판</a>&nbsp;&nbsp;&nbsp;| &nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/EnrollForm.pj\">프로젝트 업로드</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("	                    \n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/myPage.me?userNo=");
      out.print( loginUser.getUserNo() );
      out.write("\">\n");
      out.write("	                    <img src=\"./resources/img/user.png\" id=\"userImg\" style=\"width: 15px; height:15px;\">&nbsp\n");
      out.write("	                    ");
      out.print( loginUser.getNickname() );
      out.write(" 님</a>&nbsp;&nbsp;&nbsp;\n");
      out.write("	                    <a href=\"");
      out.print( contextPath );
      out.write("/logout.me\">로그아웃</a>\n");
      out.write("	                </div>\n");
      out.write("	            </div>\n");
      out.write("            ");
 } 
      out.write(" \n");
      out.write("		</div>\n");
      out.write("        \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("    \n");
      out.write("		var msg = \"");
      out.print( alertMsg );
      out.write("\";\n");
      out.write("		\n");
      out.write("		var loginForm = document.getElementById(\"login-form\");\n");
      out.write("     \n");
      out.write("		console.log(msg);\n");
      out.write("     \n");
      out.write("		if(msg != \"null\"){\n");
      out.write("			alert(msg);\n");
      out.write("          ");
 session.removeAttribute("alertMsg"); 
      out.write("\n");
      out.write("		}\n");
      out.write("     	\n");
      out.write("	</script>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("	\n");
      out.write("    <div id=\"outer\">\n");
      out.write("\n");
      out.write("        <div id=\"login\">\n");
      out.write("\n");
      out.write("            <form id=\"login-form\" method=\"post\" action=\"");
      out.print( contextPath );
      out.write("/login.me\">\n");
      out.write("\n");
      out.write("                <p id=\"loginP\">로그인</p>\n");
      out.write("\n");
      out.write("                <input type=\"text\" name=\"userId\" id=\"userId\" placeholder=\"아이디\" required>\n");
      out.write("                <input type=\"password\" name=\"userPwd\" id=\"userPwd\" placeholder=\"비밀번호\" required><br><br>\n");
      out.write("                <input type=\"checkbox\" name=\"idSave\" id=\"idSave\"><span id=\"idSaveP\">아이디 저장</span> &nbsp;&nbsp;\n");
      out.write("                <a id=\"searchIdPwd\" href=\"");
      out.print( contextPath );
      out.write("/findUserIdForm.me\">아이디/비밀번호 찾기</a><br><br>\n");
      out.write("\n");
      out.write("                <button id=\"loginBtn\" onclick=\"login()\">로그인</button><br><br>\n");
      out.write("\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("            <hr id=\"hr\">\n");
      out.write("            <br>\n");
      out.write("            <span style=\"font-size: 15px;\">WeFun:D 계정이 없다면</span>&nbsp;&nbsp;\n");
      out.write("            <a id=\"signUp\" href=\"");
      out.print( contextPath );
      out.write("/signUpForm.me\">회원가입</a>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("\n");
      out.write("        /*쿠키값저장코드*/   \n");
      out.write("        function setCookie(cookieName, value, exdays){\n");
      out.write("            var exdate = new Date();\n");
      out.write("            exdate.setDate(exdate.getDate() + exdays);\n");
      out.write("            var cookieValue = escape(value) + ((exdays==null) ? \"\" : \"; expires=\" + exdate.toGMTString());\n");
      out.write("            document.cookie = cookieName + \"=\" + cookieValue;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function deleteCookie(cookieName){\n");
      out.write("            var expireDate = new Date();\n");
      out.write("            expireDate.setDate(expireDate.getDate() - 1);\n");
      out.write("            document.cookie = cookieName + \"= \" + \"; expires=\" + expireDate.toGMTString();\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        function getCookie(cookieName) {\n");
      out.write("            cookieName = cookieName + '=';\n");
      out.write("            var cookieData = document.cookie;\n");
      out.write("            var start = cookieData.indexOf(cookieName);\n");
      out.write("            var cookieValue = '';\n");
      out.write("            if(start != -1){\n");
      out.write("                start += cookieName.length;\n");
      out.write("                var end = cookieData.indexOf(';', start);\n");
      out.write("                if(end == -1)end = cookieData.length;\n");
      out.write("                cookieValue = cookieData.substring(start, end);\n");
      out.write("            }\n");
      out.write("            return unescape(cookieValue);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var userId = getCookie(\"userId\");//저장된 쿠기값 가져오기\n");
      out.write("        $(\"input[name='userId']\").val(userId); \n");
      out.write("        \n");
      out.write("        if($(\"input[name='userId']\").val() != \"\"){ \n");
      out.write("            $(\"#idSave\").attr(\"checked\", true); \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        $(\"#idSave\").change(function(){ \n");
      out.write("            if($(\"#idSave\").is(\":checked\")){ \n");
      out.write("                var userId = $(\"input[name='userId']\").val();\n");
      out.write("                setCookie(\"userId\", userId, 7); \n");
      out.write("            }else{ \n");
      out.write("                deleteCookie(\"userId\");\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        $(\"input[name='userId']\").keyup(function(){ \n");
      out.write("            if($(\"#idSave\").is(\":checked\")){ \n");
      out.write("                var userId = $(\"input[name='userId']\").val();\n");
      out.write("                setCookie(\"userId\", userId, 7); \n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        /*로그인 실패*/\n");
      out.write("        function login(){\n");
      out.write("            var errorMsg = \"");
      out.print( errorMsg );
      out.write("\";\n");
      out.write("        \n");
      out.write("            console.log(errorMsg);\n");
      out.write("        \n");
      out.write("            if(errorMsg != \"null\"){\n");
      out.write("                alert(errorMsg);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("    	}\n");
      out.write("\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("        ");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Document</title>\n");
      out.write("    <style>\n");
      out.write("        div{\n");
      out.write("            box-sizing : border-box;\n");
      out.write("            /*border : 1px solid red;*/\n");
      out.write("        }\n");
      out.write("        .wrap{\n");
      out.write("            width : 1000px;\n");
      out.write("            height : 80px;\n");
      out.write("            margin : auto;\n");
      out.write("        }\n");
      out.write("        .warp > div{width : 100%;}\n");
      out.write("        \n");
      out.write("        /*footer*/\n");
      out.write("        #footer{height: 130px; text-align: left;}\n");
      out.write("        #footer > div{height : 100%; float : left;}\n");
      out.write("        #footer1{width: 60%; margin-left: 25px; }\n");
      out.write("        #footer2{ width: 20%; margin-left: 50px;}\n");
      out.write("        #footer p{font-size: 12px;}\n");
      out.write("        #footer a{text-decoration: none; color: rgb(63, 74, 224);}\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"wrap\">\n");
      out.write("    \n");
      out.write("        <div id=\"footer\">\n");
      out.write("\n");
      out.write("            <hr>\n");
      out.write("\n");
      out.write("            <div id=\"footer1\"> \n");
      out.write("                <p style=\"font-size: 15px;\">WeFun:D</p>\n");
      out.write("                <p>주소 : 서울특별시 중구 남대문로 120 대일빌딩 2F</p>\n");
      out.write("                <p>대표 : 이승철</p>\n");
      out.write("            </div>\n");
      out.write("            <div id=\"footer2\"> \n");
      out.write("                <p style=\"font-size: 15px;\"><a href=\"");
      out.print(request.getContextPath());
      out.write("/list.not?cpage=1\">고객센터</a></p>\n");
      out.write("                <p>이용약관</p>\n");
      out.write("                <p>개인정보처리방침</p>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("            <div id=\"footer3\"> \n");
      out.write("                <p style=\"font-size: 15px;\">운영시간</p>\n");
      out.write("                <p>평일 10:00~17:00</p>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
